### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by Yutix** [supersam654/Poodle-Checker#1]
If i not set port, my output is:
Traceback (most recent call last):
  File "checker.py", line 106, in <module>
    main()
  File "checker.py", line 93, in main
    result = test_server(hostname, port, ssl.PROTOCOL_SSLv3, timeout)
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

And if i set port, that not give output

**Comment by leeorichi** [comment]
the same test

AttributeError: module 'ssl' has no attribute 'PROTOCOL_SSLv3'
